[package]
name = "frontend"
version = "0.1.0"
edition = "2024"


[dependencies]
logos = "0.15.0"
ariadne.workspace = true
thiserror.workspace = true
bincode.workspace = true
serde.workspace = true
sirius.workspace = true
